---
- name: Cluster prep
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - role: prereq
    - role: airgap
    - role: raspberrypi

- name: Setup K3S server
  hosts: server
  become: true
  roles:
    - role: k3s_server

- name: Setup K3S agent
  hosts: agent
  become: true
  roles:
    - role: k3s_agent

- name: Installer Helm
  hosts: server
  become: true
  roles:
    - role: geerlingguy.helm
      vars:
        helm_version: v3.15.2

- name: Déployer Argo CD
  hosts: server
  become: true
  roles:
    - role: argocd
