---
collections:
  - name: community.general
  - name: ansible.posix
  - name: community.kubernetes
  - name: kubernetes.core
    version: ">=2.4.0"
roles:
  - name: geerlingguy.helm
    version: 1.0.1
