---
collections:
  - name: community.general
  - name: ansible.posix
  - name: community.kubernetes
  - name: kubernetes.core
roles:
  - name: xunholy.argocd      # pour l’install Argo CD (optionnel)
