#cloud-config
hostname: ${hostname}
timezone: Europe/Paris
users:
  - default
  - name: ubuntu
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: ansible
    groups: sudo
    shell: /bin/bash
    ssh_authorized_keys:
      - ${ssh_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
package_update: true
packages:
  - qemu-guest-agent
  - net-tools
  - curl
runcmd:
  - systemctl enable qemu-guest-agent
  - systemctl start qemu-guest-agent
  - echo "done" > /tmp/cloud-config.done
